modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "candlelight"
version = "${version}"
displayName = "Candlelight Dinner"
authors = "satisfy_u, Cristelknight, BaumeisterJo"
description = '''
A Food Themed Expansion for the 'Let's Do Wine' Mod focusing on cooking with Wine
'''
logoFile = "pack.png"

[[dependencies.candlelight]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.candlelight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.candlelight]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.candlelight]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.3,)"
ordering = "AFTER"
side = "BOTH"