modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "candlelight"
version = "${version}"
displayName = "Candlelight Dinner"
authors = "satisfy_u, Cristelknight, BaumeisterJo"
description = '''
A Food Themed Expansion for the 'Let's Do Wine' Mod focusing on cooking with Wine
'''
#logoFile = "assets/candlelight/icon.png"

[[dependencies.candlelight]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.candlelight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.candlelight]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"